WebApplicationAPP/WebApplicationAPP/Models/Calculadora.cs
namespace WebApplicationAPP.Models
{
    public class CalculadoraViewModel
    {
        public double valor1 { get; set; }

        public double valor2 { get; set; }

        public double resultado { get; set; }

        public string operacion { get; set; }
        //?????
    }
}

WebApplicationAPP/WebApplicationAPP/Models/Clientes.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplicationAPP.Models
{
        [Table("Cliente_JafethPoveda")]

        public class Clientes
        {

        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }

        public string Telefono { get; set; }

        public string Direccion {  get; set; }

        public DateTime FechaRegistro { get; set; }

        public bool Estado { get; set; }=false;

        }

}

WebApplicationAPP/WebApplicationAPP/Models/ErrorViewModel.cs
namespace WebApplicationAPP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplicationAPP/WebApplicationAPP/Models/Producto.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplicationAPP.Models
{

    [Table("Inventario_JafethPoveda")]
    public class Producto
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public int Stock { get; set; }
        public string Categoria { get; set; }
        public DateTime FechaRegistro { get; set; }
        public bool Estado { get; set; } = false;

    }
}

WebApplicationAPP/WebApplicationAPP/Controllers/CalculadoraController.cs
using Microsoft.AspNetCore.Mvc;
using System.Reflection;
using WebApplicationAPP.Models;

namespace WebApplicationAPP.Controllers
{
    public class CalculadoraController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(new CalculadoraViewModel());
        }

        [HttpPost]
        public IActionResult Index(CalculadoraViewModel modelo)
        {

            if (modelo.operacion == "suma")
            {
                modelo.resultado = modelo.valor1 + modelo.valor2;
            }
            else if (modelo.operacion == "resta")
            {
                modelo.resultado = modelo.valor1 - modelo.valor2;
            }
            else if (modelo.operacion == "multiplicacion")
            {
                modelo.resultado = modelo.valor1 * modelo.valor2;
            }
            else if (modelo.operacion == "division")
            {
                modelo.resultado = modelo.valor1 / modelo.valor2;
            }

            return View(modelo);
        }
    }
}

WebApplicationAPP/WebApplicationAPP/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationAPP.Bussines;
using WebApplicationAPP.Models;


namespace WebApplicationAPP.Controllers
{
    public class ClientesController : Controller
    {
        private readonly ClientesBussiness _clientesBussiness;

        public ClientesController(ClientesBussiness clientesBussiness)
        {
            _clientesBussiness = clientesBussiness;
        }


        public IActionResult Index()
        {
            return View(_clientesBussiness.GetAllPersonas());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Clientes clientes)
        {
            if (!ModelState.IsValid)
            {
                return View(clientes);
            }
            _clientesBussiness.AddPersona(clientes);

            return RedirectToAction(nameof(Index));
        }



        public IActionResult Edit(int id)
        {
            return View(_clientesBussiness.GetPersonaById(id));
        }


        public IActionResult Details(int id)
        {
            return View(_clientesBussiness.GetPersonaById(id));
        }


        [HttpPost]
        public IActionResult Edit(Clientes clientes)
        {
            _clientesBussiness.UpdatePersona(clientes);
            return RedirectToAction("Index");
        }


        public IActionResult Delete(int id)
        {
            return View(_clientesBussiness.GetPersonaById(id));
        }


        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmar(int id)
        {
            _clientesBussiness.DeletePersona(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

WebApplicationAPP/WebApplicationAPP/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebApplicationAPP.Models;

namespace WebApplicationAPP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplicationAPP/WebApplicationAPP/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplicationAPP.Bussines;
using WebApplicationAPP.Models;


namespace WebApplicationAPP.Controllers
{
    public class ProductoController : Controller
    {
        private readonly ProductoBussiness _productoBussiness;

        public ProductoController(ProductoBussiness productoBussiness)
        {
            _productoBussiness = productoBussiness;
        }


        public IActionResult Index()
        {
            return View(_productoBussiness.GetAllProducto());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Producto producto)
        {
            if (!ModelState.IsValid)
            {
                return View(producto);
            }
            _productoBussiness.AddProducto(producto);

            return RedirectToAction(nameof(Index));
        }



        public IActionResult Edit(int id)
        {
            return View(_productoBussiness.GetProductoById(id));
        }


        public IActionResult Details(int id)
        {
            return View(_productoBussiness.GetProductoById(id));
        }


        [HttpPost]
        public IActionResult Edit(Producto producto)
        {
            _productoBussiness.UpdateProducto(producto);
            return RedirectToAction("Index");
        }


        public IActionResult Delete(int id)
        {
            return View(_productoBussiness.GetProductoById(id));
        }


        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmar(int id)
        {
            _productoBussiness.DeleteProducto(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

WebApplicationAPP/WebApplicationAPP/Views/Calculadora/Index.cshtml
@model WebApplicationAPP.Models.CalculadoraViewModel

<form asp-action="Index" method="post">
    <div class="input-group mb-3">
        <input asp-for="valor1" type="number" class="form-control" placeholder="Numeros" aria-label="Recipient's username" aria-describedby="basic-addon2">
        <span class="input-group-text" id="basic-addon2">Dato 1</span>
    </div>

    <div class="input-group mb-3">
        <input asp-for="valor2" type="number" class="form-control" placeholder="Numeros" aria-label="Recipient's username" aria-describedby="basic-addon2">
        <span class="input-group-text" id="basic-addon2">Dato 2</span>
    </div>


    <div class="input-group mb-3">
        <select asp-for="operacion">
            <option value="">Selecciona tu operacion</option>
            <option value="suma">Suma</option>
            <option value="resta">Resta</option>
            <option value="multiplicacion">Multiplicacion</option>
            <option value="division">Division</option>
        </select>
    </div>

    <button type="submit" class="btn btn-secondary">Calcular</button>
</form>


@if (Model.resultado != null)
{
    <div class="alert alert-info" role="alert">
        El resultado es: @Model.resultado
    </div>
}


@* <button type="button" onclick="calcular('suma')'" class="btn btn-primary">Sumar</button>
<button type="button" class="btn btn-secondary">Secondary</button>
<button type="button" class="btn btn-success">Success</button>
<button type="button" class="btn btn-danger">Danger</button> *@
@* 


        public double valor1 { get; set; }

        public double valor2 { get; set; }

        public double resultado { get; set; } *@

WebApplicationAPP/WebApplicationAPP/Views/Clientes/Create.cshtml
@model WebApplicationAPP.Models.Clientes

@{
    ViewBag.Title = "Registra Cliente";
}

<h2>Registrar Cliente</h2>

<form asp-action="Create" method="post">


    <div class="mb-3">
        <label for="" class="form-label">Nombre</label>
        <input type="text"
               class="form-control"
               aria-describedby="helpId"
               placeholder="Ingrese su nombre"
               asp-for="Nombre" />
        <small id="helpId" class="form-text text-muted">Help Nombre</small>
    </div>


    <div class="mb-3">
        <label for="" class="form-label">Correo electronico</label>
        <input type="text"
               class="form-control"
               aria-describedby="helpId"
               placeholder="Ingrese su correo electronico"
               asp-for="Correo" />
        <small id="helpId" class="form-text text-muted">Help Apellido</small>
    </div>


    <div class="mb-3">
        <label for="" class="form-label">Telefono</label>
        <input type="number"
               class="form-control"
               aria-describedby="helpId"
               placeholder="Ingrese su numero de telefono"
               asp-for="Telefono" />
        <small id="helpId" class="form-text text-muted">Help Apellido</small>
    </div>

    
    <div class="mb-3">
        <label for="" class="form-label">Telefono</label>
        <input type="text"
               class="form-control"
               aria-describedby="helpId"
               placeholder="Ingrese su direccion"
               asp-for="Direccion" />
        <small id="helpId" class="form-text text-muted">Help Direccion</small>
    </div>

    <div class="mb-3">
        <label class="form-label">Fecha de registro</label>
        <input asp-for="FechaRegistro"
               type="date"
               class="form-control"
               value="@DateTime.Now.ToString("yyyy-MM-dd")"
               readonly />
    </div>

    <div class="mb-3">
        <label for="" class="form-label">Estado</label>

        <div class="form-group">
            <input aria-describedby="helpId"
                   placeholder="Ingrese su nombre"
                   asp-for="Estado" />
        </div>

        <small id="helpId" class="form-text text-muted">Help Estado</small>
    </div>

    <div class="mb-3">
        <a asp-action="Index"
           class="btn btn-danger"
           role="button">Cancelar</a>

        <button type="submit"
                class="btn btn-primary">
            Enviar
        </button>
    </div>

</form>

WebApplicationAPP/WebApplicationAPP/Views/Clientes/Delete.cshtml
@model WebApplicationAPP.Models.Clientes

<h1>Eliminar Cliente</h1>
<p>¿Desea eliminar el cliente?</p>

<form method="post">

    <input type="hidden" asp-for="Id" name="Id" required />

    <label for="Nombre">Nombre:</label>
    <input type="text" asp-for="Nombre" name="Nombre" required />

    <label for="CorreoElectronico">Correo Electrónico:</label>
    <input type="email" asp-for="Correo" name="CorreoElectronico" required />

    <label for="Telefono">Teléfono:</label>
    <input type="text" asp-for="Telefono" name="Telefono" required />

    <label for="Direccion">Dirección:</label>
    <input type="text" asp-for="Direccion" name="Direccion" required />

    <button type="submit" class="btn btn-danger">Si</button>
    <a asp-action="Index">Cancelar</a>

</form>

WebApplicationAPP/WebApplicationAPP/Views/Clientes/Details.cshtml
@model WebApplicationAPP.Models.Clientes

<h1>Detalles</h1>

<p>
    Id: @Model.Id
</p>

<p>
    Nombre: @Model.Nombre
</p>

<p>
    Correo Electrónico: @Model.Correo
</p>

<p>
    Teléfono: @Model.Telefono
</p>

<p>
    Dirección: @Model.Direccion
</p>

<p>
    Fecha de registro: @Model.FechaRegistro
</p>

<p>
    Activo = @Model.Estado
</p>

<a asp-action="Index">Regresar a la lista</a>

WebApplicationAPP/WebApplicationAPP/Views/Clientes/Edit.cshtml
@model WebApplicationAPP.Models.Clientes

@{
    ViewBag.Title = "Cliente Persona";
}

<h2>Editar Cliente</h2>

<form asp-action="Edit" method="post">

<div class="mb-3">
    <label for="" class="form-label">Nombre</label>
    <input type="text"
           class="form-control"
           aria-describedby="helpId"
           placeholder="Ingrese su nombre"
           asp-for="Nombre" />
    <small id="helpId" class="form-text text-muted">Help Nombre</small>
</div>


<div class="mb-3">
    <label for="" class="form-label">Correo electronico</label>
    <input type="text"
           class="form-control"
           aria-describedby="helpId"
           placeholder="Ingrese su correo electronico"
           asp-for="Correo" />
    <small id="helpId" class="form-text text-muted">Help Correo</small>
</div>


<div class="mb-3">
    <label for="" class="form-label">Telefono</label>
    <input type="number"
           class="form-control"
           aria-describedby="helpId"
           placeholder="Ingrese su numero de telefono"
           asp-for="Telefono" />
    <small id="helpId" class="form-text text-muted">Help Telefono</small>
</div>

    <div class="mb-3">
        <label for="" class="form-label">Telefono</label>
        <input type="text"
               class="form-control"
               aria-describedby="helpId"
               placeholder="Ingrese su direccion"
               asp-for="Direccion" />
        <small id="helpId" class="form-text text-muted">Help Direccion</small>
    </div>

    <div class="mb-3">
        <label class="form-label">Fecha de registro</label>
        <input asp-for="FechaRegistro"
               type="date"
               class="form-control"
               value="@DateTime.Now.ToString("yyyy-MM-dd")"
               readonly />
    </div>

<div class="mb-3">
    <label for="" class="form-label">Estado</label>

    <div class="form-group">
        <input aria-describedby="helpId"
               placeholder="Ingrese su nombre"
               asp-for="Estado" />
    </div>

    <small id="helpId" class="form-text text-muted">Help Estado</small>
</div>

    <div class="mb-3">
        <a asp-action="Index"
           class="btn btn-danger"
           role="button">Cancelar</a>

        <button type="submit"
                class="btn btn-primary">
            Enviar
        </button>
    </div>

</form>

WebApplicationAPP/WebApplicationAPP/Views/Clientes/Index.cshtml
@model IEnumerable<WebApplicationAPP.Models.Clientes>

@{
    ViewBag.Title = "Clientes ";
}

<h1>Lista de Clientes</h1>

<a class="btn btn-primary"
   asp-action="Create"
   role="button">Crear</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Estado</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var clientes in Model)
        {
            <tr>
                <td>@clientes.Id</td>
                <td>@clientes.Nombre</td>
                <td>@clientes.Estado</td>
                <td>

                    <a class="btn btn-success"
                       asp-action="Details" asp-route-id="@clientes.Id"
                       role="button">Detalles</a>

                    <a class="btn btn-warning"
                       asp-action="Edit" asp-route-id="@clientes.Id"
                       role="button">Editar</a>

                    <a class="btn btn-danger"
                       asp-action="Delete" asp-route-id="@clientes.Id"
                       role="button">Eliminar</a>
                    @* <a asp-action="Details" asp-route-id="@clientes.Id">Detalles</a> | *@
                    @* <a asp-action="Edit" asp-route-id="@clientes.Id">Editar</a> | *@
                    @* <a asp-action="Delete" asp-route-id="@clientes.Id">Eliminar</a> *@
                </td>
            </tr>
        }
    </tbody>

WebApplicationAPP/WebApplicationAPP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplicationAPP/WebApplicationAPP/Views/Producto/Create.cshtml
@model WebApplicationAPP.Models.Producto

<h1>Crear Producto</h1>

<form method="post">

    <label for="Nombre">Nombre:</label>
    <input type="text" asp-for="Nombre" name="Nombre" required />

    <label for="Descripcion">Descripción:</label>
    <input type="text" asp-for="Descripcion" name="Descripcion" required />

    <label for="Categoria">Categoría:</label>
    <input type="text" asp-for="Categoria" name="Categoria" required />

    <label for="Precio">Precio:</label>
    <input type="number" asp-for="Precio" name="Precio" step="0.01" required />

    <label for="Stock">Stock:</label>
    <input type="number" asp-for="Stock" name="Stock" required />

    <label for="FechaDeIngreso">Fecha de ingreso:</label>
    <input type="datetime-local" asp-for="FechaRegistro" name="FechaDeIngreso" value="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")" required />

    <label for="Activo">Activo:</label>
    <input type="checkbox" asp-for="Estado" checked />

    <button type="submit" class="btn btn-primary">Crear</button>

</form>

WebApplicationAPP/WebApplicationAPP/Views/Producto/Delete.cshtml
@model WebApplicationAPP.Models.Producto


<h1>Eliminar Producto</h1>
<p>Desea eliminar el producto?</p>
<form method="post">

    <input type="hidden" asp-for="Id" name="Id" required />


    <label for="Nombre">Nombre:</label>
    <input type="text" asp-for="Nombre" name="Nombre" required />

    <label for="Precio">Precio:</label>
    <input type="number" asp-for="Precio" name="Precio" step="0.01" required />

    <label for="Stock">Stock:</label>
    <input type="number" asp-for="Stock" name="Stock" required />

    <button type="submit" class="btn btn-danger">Si</button>
    <a asp-action="Index">Cancelar</a>
</form>

WebApplicationAPP/WebApplicationAPP/Views/Producto/Details.cshtml
@model WebApplicationAPP.Models.Producto


<h1>Detalles</h1>

<p>
    Id: @Model.Id    
</p>

<p>
    Nombre: @Model.Nombre
</p>

<p>
    Precio: @Model.Precio
</p>

<p>
    Stock: @Model.Stock
</p>

<p>
    Descripcion: @Model.Descripcion
</p>

<p>
    Categoria: @Model.Categoria
</p>

<p>
    Fecha de ingreso: @Model.FechaRegistro
</p>

<p>
    Activo = @Model.Estado
</p>


<a asp-action="Index">Regresar a la lista</a>

WebApplicationAPP/WebApplicationAPP/Views/Producto/Edit.cshtml
@model WebApplicationAPP.Models.Producto

<h1>Editar Producto</h1>

<form method="post">

    <input type="hidden" asp-for="Id" name="Id" required />

    <label for="Nombre">Nombre:</label>
    <input type="text" asp-for="Nombre" name="Nombre" required />

    <label for="Precio">Precio:</label>
    <input type="number" asp-for="Precio" name="Precio" step="0.01" required />

    <label for="Stock">Stock:</label>
    <input type="number" asp-for="Stock" name="Stock" required />

    <label for="Descripcion">Descripcion:</label>
    <input type="text" asp-for="Descripcion" name="Descripcion" required />

    <label for="Categoria">Categoria:</label>
    <input type="text" asp-for="Categoria" name="Categoria" required />

    <label for="FechaDeIngreso">Fecha de ingreso:</label>
    <input type="datetime-local" asp-for="FechaRegistro" name="FechaDeIngreso" required />

    <label for="Activo">Activo:</label>
    <input type="checkbox" asp-for="Estado" />

    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a asp-action="Index">Cancelar</a>
</form>

WebApplicationAPP/WebApplicationAPP/Views/Producto/Index.cshtml
@model IEnumerable<WebApplicationAPP.Models.Producto>

@{
    ViewBag.Title = "Producto ";
}

<h1>Lista de productos</h1>

<a class="btn btn-primary"
   asp-action="Create"
   role="button">Crear</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Stock</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>


    @foreach (var producto in Model)
    {
        <tr>
            <td>@producto.Id</td>
            <td>@producto.Nombre</td>
            <td>@producto.Precio</td>
            <td>@producto.Stock</td>
            <td>
                <a class="btn btn-success"
                   asp-action="Details" asp-route-id="@producto.Id"
                   role="button">Detalles</a>

                <a class="btn btn-warning"
                   asp-action="Edit" asp-route-id="@producto.Id"
                   role="button">Editar</a>

                <a class="btn btn-danger"
                   asp-action="Delete" asp-route-id="@producto.Id"
                   role="button">Eliminar</a>
            </td>
        </tr>
    }


  
 
</table>

WebApplicationAPP/WebApplicationAPP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationAPP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationAPP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplicationAPP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculadora" asp-action="Index">Calculadora</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Producto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - WebApplicationAPP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>